theme = "rose_pine"

[editor]
# line-number = "relative"
mouse = true

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.insert]
j = { j = "normal_mode", k = "normal_mode" }

[keys.normal]
"S-k" = "hover"
"S-g" = "goto_last_line"
"S-4" = "goto_line_end"
"ret" = ["open_below", "normal_mode"] # Maps the enter key to open_below then re-enter normal mode

[keys.select]
"S-g" = "goto_last_line"
