[[language]]
name = "latex"
language-server = { command = "ltex-ls" }

[[language]]
name = "lua"
language-server = { command = "lua-language-server" }

[[language]]
name = "markdown"
language-server = { command = "ltex-ls" }
file-types = ["md"]
scope = "source.markdown"
roots = []

[[language]]
name = "rust"
language-server = { command = "rustup", args = [
  "run",
  "nightly",
  "rust-analyzer",
] }

[[language]]
name = "typescript"
auto-format = true
language-server = { command = "deno", args = ["lsp"] }
config = { deno = { enable = true, lint = true } }
indent = { tab-width = 2, unit = "\t" }

[[language]]
name = "javascript"
auto-format = true
language-server = { command = "deno", args = ["lsp"] }
config = { deno = { enable = true, lint = true } }
indent = { tab-width = 2, unit = "\t" }
