# attribute = "lilac"
"attribute" = "#dc7759"
keyword = "keyword"
# use = "keyword"
# mod = "keyword"
# "keyword.directive" = "lilac" # -- preprocessor comments (#if in C)
"keyword.other" = "keyword"
"keyword.control" = "control"
"keyword.control.import" = "keyword"
"keyword.function" = "keyword"
# "keyword.operator" = "control"
"keyword.operator" = "keyword"
"namespace" = "function"
# namespace = "lilac"
# "punctuation" = "#dc7759"
# "punctuation.delimiter" = "#dc7759"
# punctuation = {fg = "lavender", modifiers = []}
# "punctuation.delimiter" = {fg = "lavender", modifiers = []}
punctuation = "punctuation"
"punctuation.delimiter" = {fg = "punctuation_delim", modifiers = []}
operator = {fg = "operator", modifiers = []}
# operator = "punctuation"
# "operator" = { fg = "operator", modifiers = ["bold"] }
special = "honey"
# "variable.other.member" = "white"
# "self" = "keyword"
"variable.other.member" = "property"
"variable" = "#c6b8ad"
"variable.parameter" = "#c6b8ad"
# "type" = "#dc597f"
# variable = "variable"
property = "property"
# source_file = "property"
"function.call" = "property"
# variable = "almond" # TODO: metavariables only
# "variable.parameter" = { fg = "lavender", modifiers = ["underlined"] }
# "variable.parameter" = { fg = "parameter" }
"variable.builtin" = "self"
type = "type"
"type.builtin" = { fg = "type_builtin", modifiers = [] }
# "type.builtin" = "white" # TODO: distinguish?
constructor = "ctor"
function = "function"
"function.macro" = { fg = "macro", modifiers = [] }
"function.builtin" = { fg = "macro", modifiers = [] }
# "function.macro" = "lilac"
# "function.builtin" = "white"
tag = "almond"
comment = "comment"
"comment.block.documentation" = "documentation"
constant = "const"
"constant.builtin" = "const"
string = "string"
# numeric = "#faa42c"
numeric = "const_num"
# "constant.numeric" = "#faa42c"
"constant.numeric" = "const_num"
"constant.character.escape" = "escape"
# used for lifetimes
label = "honey"

"module" = "#d32c5d"

"markup.heading" = "lilac"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.url" = { fg = "silver", modifiers = ["underlined"] }
"markup.link.text" = "almond"
"markup.raw" = "almond"

"diff.plus" = "#35bf86"
"diff.minus" = "#f22c86"
"diff.delta" = "#6f44f0"

# TODO: diferentiate doc comment
# concat (ERROR) @error.syntax and "MISSING ;" selectors for errors

"ui.background" = { bg = "midnight" }
"ui.background.separator" = { fg = "comet" }
"ui.linenr" = { fg = "line" }
"ui.linenr.selected" = { fg = "line_sel" }
"ui.statusline" = { fg = "statusline", bg = "statusline_bg" }
"ui.statusline.inactive" = { fg = "statusline", bg = "statusline_bg" }
"ui.popup" = { bg = "secondary" }
"ui.window" = { fg = "bossanova" }
"ui.help" = { bg = "ui_help_bg", fg = "text" }

# "ui.text" = { fg = "lavender" }
# "ui.text" = { fg = "text" }
"ui.text" = { fg = "ui_text" }
"ui.text.focus" = { fg = "white" }
"ui.virtual" = { fg = "comet" }

"ui.virtual.indent-guide" = { fg = "comet" }

"ui.selection" = { bg = "#540099" }
"ui.selection.primary" = { bg = "#540099" }
# "ui.selection" = { bg = "#313f4e" }
# "ui.selection.primary" = { bg = "selection" }
# TODO: namespace ui.cursor as ui.selection.cursor?
"ui.cursor.select" = { bg = "delta" }
"ui.cursor.insert" = { bg = "white" }
# "ui.cursor.match" = { fg = "#212121", bg = "#6C6999" }
"ui.cursor.match" = { bg = "delta" }
# "ui.cursor" = { modifiers = ["reversed"] }
"ui.cursor" = { bg = "delta", fg="#fcfcfc", modifiers = ["bold"] }
# fcfcfc
# bfbdb6
"ui.cursorline.primary" = { bg = "selection" }
"ui.highlight" = { bg = "selection" }

"ui.menu" = { fg = "text", bg = "secondary" }
"ui.menu.selected" = { fg = "revolver", bg = "white" }
"ui.menu.scroll" = { fg = "scroll", bg = "comet" }

diagnostic = { modifiers = ["dim"] }
# "diagnostic.hint" = { fg = "revolver", bg = "lilac" }
# "diagnostic.info" = { fg = "revolver", bg = "lavender" }
# "diagnostic.warning" = { fg = "revolver", bg = "honey" }
# "diagnostic.error" = { fg = "revolver", bg = "apricot" }

warning = "lightning"
error = "apricot"
info = "delta"
hint = "silver"

[palette]
# BlastX palette
background = "#121726"
keyword = "#24B5A8"
type = "#935cd1"
# type_builtin = "#24B5A8"
type_builtin = "#935cd1"
function = "#3398DB"
control = "#c9a022"
# control = "#efbe28"
# operator = "#C9A022"
# operator = "#efbe28"
# operator = "#24B5A8"
operator = "#2CA7C2"
# operator = "#90b0d5"
string = "#37ae6f"
parameter = "#cc71bc" # this
# parameter = "#b735ee"
# parameter = "#d3869b"

variable = "#de456b"
# variable = "#B9519E"
property = "#d26d32" # this
# property = "#9b2ec9"
# property = "#83a598"
# property = "#83a598"
self = "#24B5A8"
secondary = "#122444"
# secondary = "#0e1320"
# punctuation = "#83a598" # vis
# punctuation = "#3c495e"
# punctuation = "#56949f"
# punctuation = "#5d7189" # this
punctuation = "#3c495e" # invis
# punctuation = "#24B5A8"
punctuation_delim = "#3c495e"
# d7827e
# 575279
# 56949f
# text = "#83a598"
# text = "#56949f"
text = "#bfcbd4"
ui_text = "#90b0d5"
ui_help_bg = "#0e1320"
# statusline = "#83a598"
statusline = "#5d7189"
statusline_bg = "#0e1320"
# macro = "#8ec07c"
# macro = "#3ba3ff"
macro = "#2CA7C2"
scroll = "#3c495e"
const = "#C13838"
# const = "#59c0dc"
ctor = "#935cd1"
line = "#3c495e"
line_sel = "#5d7189"
selection = "#19284c"
# const_num = "#D26D32"
const_num = "#c9a022"
comment = "#5D7189"
documentation = "#90b0d5"



white = "#ffffff"
lilac = "#dbbfef"
lavender = "#a4a0e8"
comet = "#5a5977"
bossanova = "#452859"
midnight = "#121726"
revolver = "#281733"

silver = "#cccccc"
black_silver = "#aaaaaa"
sirocco = "#697C81"
mint = "#9ff28f"
almond = "#eccdba"
chamois = "#E8DCA0"
# honey = "#efba5d"
honey = "#C9A022"
escape = "#C13838"

apricot = "#f47868"
lightning = "#ffcd1c"
# delta = "#6F44F0"
delta = "#203c74"
