"ui.background" = { bg = "base" }
"ui.menu" = { fg = "text", bg = "overlay" }
"ui.menu.selected" = { fg = "iris", bg = "surface" }
"ui.linenr" = {fg = "subtle" }
"ui.liner.selected" = "highlightOverlay"
"ui.selection" = { bg = "highlight" }
"comment" = "subtle"
"ui.statusline" = {fg = "foam", bg = "surface" }
"ui.statusline.inactive" = { fg = "iris", bg = "surface" }
"ui.help" = { fg = "foam", bg = "surface" }
"ui.cursor" = { fg = "rose", modifiers = ["reversed"] }
"ui.text" = { fg = "text" }
"ui.text.focus" = { fg = "foam", modifiers = ["bold"]}
"ui.text.info" = {fg = "pine", modifiers = ["bold"]}
"ui.virtual" = "highlight"
"operator" = "rose"
"variable" = "text"
"constant.numeric" = "iris"
"constant" = "gold"
"attributes" = "gold"
"type" = "foam"
"ui.cursor.match" = { fg = "gold", modifiers = ["underlined"] }
"string"  = "gold"
"property" = "foam"
"constant.character.escape" = "subtle"
"function" = "rose"
"function.builtin" = "rose"
"function.method"  = "foam"
"constructor" = "gold"
"special" = "gold"
"keyword" = "pine"
"label" = "iris"
"namespace" = "pine"
"ui.popup" = { bg = "surface" }
"ui.popup.info" = { bg = "surface" }
"ui.window" = { bg = "base" }
"ui.help" = { bg = "overlay", fg = "foam" }
"text" = "text"
"diff.plus" = "foam"
"diff.delta" = "rose"
"diff.minus" = "love"

"info" = "gold"
"hint" = "gold"
"debug" = "rose"
"diagnostic" = "rose"
"error" = "love"

"markup.heading.marker" = "subtle"
"markup.heading.1" = { fg = "love", modifiers = ["bold"] }
"markup.heading.2" = { fg = "gold", modifiers = ["bold"] }
"markup.heading.3" = { fg = "rose", modifiers = ["bold"] }
"markup.heading.4" = { fg = "pine", modifiers = ["bold"] }
"markup.heading.5" = { fg = "form", modifiers = ["bold"] }
"markup.heading.6" = { fg = "fg", modifiers = ["bold"] }
"markup.list" = { fg = "love" }
"markup.bold" = { fg = "gold", modifiers = ["bold"] }
"markup.italic" = { fg = "iris", modifiers = ["italic"] }
"markup.link.url" = { fg = "pine", modifiers = ["underlined"]}
"markup.link.text" = { fg = "foam" }
"markup.quote" = { fg = "rose" }
"markup.raw" = { fg = "foam" }

[palette]
base     = "#1E1E2E"
surface  = "#302D41"
overlay  = "#302D41"
inactive = "#302D41"
subtle   = "#6E6C7E"
text     = "#D9E0EE"
love     = "#E8A2AF"
gold     = "#FAE3B0"
rose     = "#C9CBFF"
pine     = "#C9CBFF"
foam     = "#C9CBFF"
iris     = "#DDB6F2"
highlight = "#2a2837"
highlightInactive = "#211f2d"
highlightOverlay = "#3a384a"
