error = "red"
comment = "comment"
constant = "purple"
function = "green"
keyword = "pink"
type = { fg = "cyan", modifiers = ["italic"] }
string = "yellow"
variable = "foreground"
property = "foreground"
hint = {  fg = "foreground" }
diagnostic = { fg = "foreground" }
"function.builtin" = "cyan"
"ui.background" = { bg = "background" }
"ui.text" =  { fg = "foreground" }
"ui.statusline" = { fg = "foreground", bg = "bg-light" } 
"ui.statusline.inactive" = { fg = "foreground", bg = "purple" }
"ui.selection" = { bg = "selection" }
"ui.info" = { fg = "foreground", bg = "bg-light" }
"ui.info.text" = { fg = "foreground", bg="bg-light"  }
"ui.menu" = { fg = "foreground", bg = "bg-light" }
"ui.menu.selection" = { fg = "foreground", bg = "bg-light" }
"ui.window" = { fg = "foreground", bg = "bg-light" }
"ui.help" = { fg = "foreground", bg = "bg-light" }
"ui.linenr" = "comment"
"ui.linenr.selected" = "foreground"
"ui.menu.selected" = { fg =  "foreground", bg = "bg-light" }
number = "purple"
attribute = "green"
"constant.builtin" = "purple"
"ui.popup" = { fg =  "foreground", bg = "bg-light" }



namespace = "pink"

[palette]
background = "#282A36"
foreground = "#F8F8F2"
selection = "#44475A"
comment = "#6272A4"
red = "#FF5555"
orange = "#FFB86C"
yellow = "#F1FA8C"
green = "#50FA7B"
purple = "#BD93F9"
cyan = "#8BE9FD"
pink = "#FF79C6"
bg-light = "#343746"
